In [22]:
import cv2
import numpy as np
import random 
img=np.zeros([512,512,3],dtype=np.uint8)
img.fill(255)
flag="pantheon{r3sP3ct_p0w3r_B4nAna}"
for i in range(0,len(flag)):
    c=flag[i]
    pn=random.randrange(0, 512)
    color=random.randrange(0, 3)
    print(pn,color)
    img[i*10+200][pn][color]=ord(c)
    
cv2.imshow("IMG",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("White.png",img)
print(img)

400 0
402 1
68 1
124 2
407 0
276 2
148 1
157 1
85 1
62 1
264 1
192 0
414 1
182 1
142 1
415 2
128 2
430 0
124 2
335 0
133 1
129 1
456 1
200 1
120 0
413 1
137 2
172 1
380 2
221 0
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [25]:
img1=cv2.imread("White.png")
print(img1[0][0])

# print('Array:\n', Array)
file = open("file1.txt", "w+")
 
# Saving the array in a text file
content = ""

for i in img1:
    for r in i:
        content+='['
        for j in r:
            content+=str(j)
            content+=' '
        content+=']'
    content+='\n'
ans=""
for i in img1:
    for r in i:
        for j in r:
            if j != 255:
                ans+=chr(j)
print(ans)
file.write(content)
file.close()

[255 255 255]
pantheon{r3sP3ct_p0w3r_B4nAna}
